version: "3"

services:
  app1:
    build:
      context: ./node
      dockerfile: ./app.dockerfile
    environment:
      - SERVER_ID=1
      - PORT=15001
      - GRPC_HOST=server
      - GRPC_PORT=28000
      - RAND_FROM=1000
      - RAND_TO=2000
    ports:
      - "15001:15001"
  app2:
    build:
      context: ./node
      dockerfile: ./app.dockerfile
    environment:
      - SERVER_ID=2
      - PORT=15002
      - GRPC_HOST=server
      - GRPC_PORT=28000
      - RAND_FROM=3000
      - RAND_TO=4000
    ports:
      - "15002:15002"
  app3:
    build:
      context: ./node
      dockerfile: ./app.dockerfile
    environment:
      - SERVER_ID=3
      - PORT=15003
      - GRPC_HOST=server
      - GRPC_PORT=28000
      - RAND_FROM=5000
      - RAND_TO=6000
    ports:
      - "15003:15003"
  server:
    build:
      context: ./node
      dockerfile: ./server.dockerfile
    environment:
      - GRPC_PORT=28000
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "18000:80"
